Fix indentation in buildprep.
Signed-off-by: Walid M. Boudelal <wboudelal@gmail.com>

diff --git a/buildprep b/buildprep
--- a/buildprep
+++ b/buildprep
@@ -16,10 +16,10 @@ OS=$(uname -s)
 # Loop through option flags
 for optflag in "$@"
 do
-	case "$optflag" in
-	 -h|--help)
-		cat <<EOF
-$0 - prepare your system for an NTPsec source build
+    case "$optflag" in
+    -h|--help)
+        cat <<EOF
+$0 - prepare your system for a cvs-fast-export source build
 
   Options:
     -h --help    Show usage information and exit
@@ -27,22 +27,22 @@ $0 - prepare your system for an NTPsec source build
        --doc     Install dependencies for building documentation
     -a --all     Install all possible dependencies
 EOF
-		exit 0
-		;;
-	 -n|--dry-run)
-		DRYRUN="yes"
-		;;
-	 --doc)
-		DOC="yes"
-		;;
-	 -a|--all)
-		DOC="yes"
-		;;
-	 *)
-		echo "# WARNING: Unknown argument: $optflag"
-		echo "#"
-		;;
-	esac
+        exit 0
+        ;;
+    -n|--dry-run)
+        DRYRUN="yes"
+        ;;
+    --doc)
+        DOC="yes"
+        ;;
+    -a|--all)
+        DOC="yes"
+        ;;
+    *)
+        echo "# WARNING: Unknown argument: $optflag"
+        echo "#"
+        ;;
+    esac
 done
 
 cat <<EOF
@@ -61,19 +61,18 @@ EOF
 
 if [ "$DRYRUN" = "yes" ]
 then
-        # shellcheck disable=SC2209
-	do=echo
-	echo "# Run this without -n|--dry-run, as root, for actual installation."
-	echo "#You may want to run an update from your package inddex first."
-	echo "#"
+    do='echo'
+    echo "# Run this without -n|--dry-run, as root, for actual installation."
+    echo " #You may want to run an update from your package inddex first."
+    echo "#"
 else
-	do=""
-	if [ "$(id -u)" != 0 ]
-	then
-		echo "# ERROR: You must be running as root for your installer to do its thing."
-		echo "# ERROR: If you just wish to see what would be done, use the -n option."
-		exit 1
-	fi
+    do=""
+    if [ "$(id -u)" != 0 ]
+    then
+        echo "# ERROR: You must be running as root for your installer to do its thing."
+        echo "# ERROR: If you just wish to see what would be done, use the -n option."
+        exit 1
+    fi
 fi
 
 if emerge --version 2>/dev/null
@@ -106,31 +105,36 @@ then
     # Alpine Linux, musl rather than glibc
     installer=apk
     install="$do $installer add"
-elif test "$OS" = "NetBSD"
+elif command -v pacman
 then
-  if pkgin -v
-  then
-    # NetBSD binary package installer
-    installer=pkgin
-    install="$do $installer install"
-  else
-    echo "## Looks like a NetBSD system"
-    echo "## You need to setup pkgin"
-    echo "## The last page of install disk has a check-box to do it"
-    echo "## But you don't get that option on a Raspberry Pi."
-    echo "## For the Pi, do something like:"
-    echo "## pkg_add ftp://ftp.netbsd.org/pub/pkgsrc/packages/NetBSD/earmv7hf/8.0/All/pkgin-0.9.4nb8.tgz"
-    echo "## Adjust the version and arch to match your setup."
-    exit 1
-  fi
-elif test "$OS" = "FreeBSD"
+    # Arch Linux
+    installer=pacman
+    install="$do $installer -S --needed --noconfirm"
+elif [ "$OS" = "NetBSD" ]
 then
-  if pkg -v
-  then
-    # FreeBSD binary package installer
-    installer=pkg
-    install="$do $installer install"
-  fi
+    if pkgin -v
+    then
+        # NetBSD binary package installer
+        installer=pkgin
+        install="$do $installer install"
+    else
+        echo "## Looks like a NetBSD system"
+        echo "## You need to setup pkgin"
+        echo "## The last page of install disk has a check-box to do it"
+        echo "## But you don't get that option on a Raspberry Pi."
+        echo "## For the Pi, do something like:"
+        echo "## pkg_add ftp://ftp.netbsd.org/pub/pkgsrc/packages/NetBSD/earmv7hf/8.0/All/pkgin-0.9.4nb8.tgz"
+        echo "## Adjust the version and arch to match your setup."
+        exit 1
+    fi
+elif [ "$OS" = "FreeBSD" ]
+then
+    if pkg -v
+    then
+        # FreeBSD binary package installer
+        installer=pkg
+        install="$do $installer install"
+    fi
 else
     echo "# ERROR: Package manager unidentified - Unsupported operating system"
     exit 1
@@ -141,75 +145,83 @@ echo ""
 main () {
     # Prerequisites to build the daemon: bison, pps-tools, service libraries
     case $installer in
-	apk)
-	    echo "Not yet supported" >&2
-	    exit 1
-	    ;;
-	apt)
-	    # tzdata needs to be installed explicitly so it won't try an interactive
-	    # condfiguration when pulled as a dependency.  This package doesn't care
-	    # whethe your Python is 2.x or 3.x.
-	    $install tzdata
-	    $install make grep sed gcc bison flex python git rcs cvs pylint cppcheck shellcheck
-	    ;;
-	emerge)
-	    echo "Not yet supported" >&2
-	    exit 1
-	    ;;
-	pkgin)
-	    echo "Not yet supported" >&2
-	    exit 1
-	    ;;
-	pkg)
-	    echo "Not yet supported" >&2
-	    exit 1
-	    ;;
-	yum|dnf)
-	    echo "Not yet supported" >&2
-	    exit 1
-	    ;;
-	yast)
-	    echo "Not yet supported" >&2
-	    exit 1
-	    ;;
-	zypper)
-	    echo "Not yet supported" >&2
-	    exit 1
-	    ;;
+    apk)
+        echo "Not yet supported" >&2
+        exit 1
+        ;;
+    apt)
+        # tzdata needs to be installed explicitly so it won't try an interactive
+        # configuration when pulled as a dependency.  This package doesn't care
+        # whether your Python is 2.x or 3.x.
+        $install tzdata
+        $install make grep sed gcc bison flex python git rcs cvs pylint cppcheck shellcheck
+        ;;
+    emerge)
+        echo "Not yet supported" >&2
+        exit 1
+        ;;
+    pacman)
+        $install tzdata
+        $install make grep sed gcc bison flex python git rcs cvs \
+        python-pylint cppcheck shellcheck
+        ;;
+    pkgin)
+        echo "Not yet supported" >&2
+        exit 1
+        ;;
+    pkg)
+        echo "Not yet supported" >&2
+        exit 1
+        ;;
+    yum|dnf)
+        echo "Not yet supported" >&2
+        exit 1
+        ;;
+    yast)
+        echo "Not yet supported" >&2
+        exit 1
+        ;;
+    zypper)
+        echo "Not yet supported" >&2
+        exit 1
+        ;;
     esac
 }
 
 doc () {
-	# prerequisites to build documentation
-	case $installer in
-	 apk)
-	     echo "Not yet supported" >&2
-	     exit 1
-	     ;;
-	 apt)
-	     $install asciidoc
-	     ;;
-	 emerge)
-	     echo "Not yet supported" >&2
-	     exit 1
-	     ;;
-	 pkgin)
-	     echo "Not yet supported" >&2
-	     exit 1
-	     ;;
-	 pkg)
-	     echo "Not yet supported" >&2
-	     exit 1
-	     ;;
-	yum|dnf)
-	     echo "Not yet supported" >&2
-	     exit 1
-	     ;;
-	 yast|zypper)
-	     echo "Not yet supported" >&2
-	     exit 1
-	     ;;
-	esac
+    # prerequisites to build documentation
+    case $installer in
+    apk)
+        echo "Not yet supported" >&2
+        exit 1
+        ;;
+    apt)
+        $install asciidoc
+        ;;
+    emerge)
+        echo "Not yet supported" >&2
+        exit 1
+        ;;
+    pacman)
+        $install asciidoc
+        ;;
+    pkgin)
+        echo "Not yet supported" >&2
+        exit 1
+        ;;
+    pkg)
+        echo "Not yet supported" >&2
+        exit 1
+        ;;
+    yum|dnf)
+        echo "Not yet supported" >&2
+        exit 1
+        ;;
+    yast|zypper)
+        echo "Not yet supported" >&2
+        exit 1
+        ;;
+    esac
 }
 
 # Main sequence
@@ -217,10 +229,10 @@ main
 
 if [ "$DOC" = "yes" ]
 then
-	doc
+    doc
 else
-	echo ""
-	echo "# Skipping documentation dependencies [--doc]"
+    echo ""
+    echo "# Skipping documentation dependencies [--doc]"
 fi
 
 echo ""
